//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hitcom_AccountingEquipment
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentCard()
        {
            this.Inventory = new HashSet<Inventory>();
            this.Repair = new HashSet<Repair>();
        }
    
        public int id { get; set; }
        public string InventNumber { get; set; }
        public System.DateTime DateOfDelivery { get; set; }
        public int FK_Equipment_id { get; set; }
        public int FK_StatusOfEquipment_id { get; set; }
        public string SerialNumber { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual StatusOfEquipment StatusOfEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair> Repair { get; set; }
    }
}
