//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hitcom_AccountingEquipment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.EquipmentCard = new HashSet<EquipmentCard>();
        }
    
        public int id { get; set; }
        public int FK_Nomenclature_id { get; set; }
        public int FK_Manufacturer_id { get; set; }
        public string Model { get; set; }
        public int LifeTime { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Nomenclature Nomenclature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentCard> EquipmentCard { get; set; }
    }
}
